[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "A safe(r) wrapper around the lammps C bindings."
!!LICENSE-GPL
!!DEFAULT-EDITION

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-structure { features = ["serde-support"] }
!!rsp2-array-types { features = ["serde-support"] }
!!lammps-sys { features = ["exceptions", "package-user-omp"] }

# This should be a dev-dependency, but see this bug:
# https://github.com/rust-lang/cargo/issues/6915
!!rsp2-assert-close

!!log
!!lazy-static
!!chrono
!!failure
!!slice-of-array
!!mpi { optional = true }

[[example]]
name = "airebo"
[[example]]
name = "zero"
[[example]]
name = "link-test"
[[example]]
name = "airebo-mpi"
required-features = ["mpi-support"]
[[example]]
name = "link-test-mpi"
required-features = ["mpi-support"]
[[example]]
name = "zero-mpi"
required-features = ["mpi-support"]

[features]
default = []

!!NIGHTLY-FEATURE-LINE

# FIXME
# Features for optional deps, because the implicit features defined by deps do not scale well.
# For now, THESE are what you should toggle in dependent crates.
#
# Once namespaced-features are stabilized, these features will be renamed after the deps.
# see https://github.com/rust-lang/cargo/issues/1286 (problem and proposal)
#     https://github.com/rust-lang/cargo/issues/5565 (tracking issue, of sorts)
mpi-support = ["mpi", "lammps-sys/mpi"]
