[package]
name = "agnr_gen"
version = "0.1.0"
authors = ["Colin Daniels <colin.r.daniels@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9"
nalgebra = "0.23"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vasp-poscar = "0.3"
clap = "3.0.0-beta.2"
